#Word embedding

Word embedding is a deep learning technique that represents words as dense, real-valued vectors in a multi-dimensional space, where words with similar meanings have similar vector representations. This method allows deep learning models to understand the semantic and syntactic relationships between words, which is crucial for natural language processing (NLP) tasks like text classification and sentiment analysis

In [14]:
import numpy as np

docs = [
    'go team go',
    'champions champions',
    'goal goal goal',
    'we will win this match',
    'defense defense defense',
    'messi messi',
    'ronaldo ronaldo',
    'neymar neymar',
    'let’s go boys',
    'victory is ours'
]


In [15]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)

In [16]:
len(tokenizer.word_index)

18

In [17]:
tokenizer.word_index

{'go': 1,
 'goal': 2,
 'defense': 3,
 'champions': 4,
 'messi': 5,
 'ronaldo': 6,
 'neymar': 7,
 'team': 8,
 'we': 9,
 'will': 10,
 'win': 11,
 'this': 12,
 'match': 13,
 'let’s': 14,
 'boys': 15,
 'victory': 16,
 'is': 17,
 'ours': 18}

In [18]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

#go team go

[[1, 8, 1],
 [4, 4],
 [2, 2, 2],
 [9, 10, 11, 12, 13],
 [3, 3, 3],
 [5, 5],
 [6, 6],
 [7, 7],
 [14, 1, 15],
 [16, 17, 18]]

In [19]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 1,  8,  1,  0,  0],
       [ 4,  4,  0,  0,  0],
       [ 2,  2,  2,  0,  0],
       [ 9, 10, 11, 12, 13],
       [ 3,  3,  3,  0,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [14,  1, 15,  0,  0],
       [16, 17, 18,  0,  0]], dtype=int32)

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(17,output_dim=2))

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.compile('adam','accuracy')

In [24]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 888ms/step
[[[-0.04420208  0.03270105]
  [-0.01872987  0.04988329]
  [-0.04420208  0.03270105]
  [-0.0423601   0.03595052]
  [-0.0423601   0.03595052]]

 [[-0.04881963 -0.04663174]
  [-0.04881963 -0.04663174]
  [-0.0423601   0.03595052]
  [-0.0423601   0.03595052]
  [-0.0423601   0.03595052]]

 [[ 0.02066511  0.04622993]
  [ 0.02066511  0.04622993]
  [ 0.02066511  0.04622993]
  [-0.0423601   0.03595052]
  [-0.0423601   0.03595052]]

 [[ 0.01874054 -0.01034682]
  [-0.01382347  0.04906489]
  [ 0.01555241 -0.03567224]
  [-0.0060704  -0.01660053]
  [ 0.01193024 -0.00805092]]

 [[ 0.00548081  0.04932607]
  [ 0.00548081  0.04932607]
  [ 0.00548081  0.04932607]
  [-0.0423601   0.03595052]
  [-0.0423601   0.03595052]]

 [[-0.00217407  0.0129332 ]
  [-0.00217407  0.0129332 ]
  [-0.0423601   0.03595052]
  [-0.0423601   0.03595052]
  [-0.0423601   0.03595052]]

 [[-0.03454845  0.02740134]
  [-0.03454845  0.02740134]
  [-0.0423601   0.03595052]
  [-0.0423601   0.0359505

In [26]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [27]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [28]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [29]:
X_train.shape

(25000, 50)

In [34]:
model = Sequential()
model.add(Embedding(input_dim= 10000, output_dim=2))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - acc: 0.5679 - loss: 0.6624 - val_acc: 0.7763 - val_loss: 0.4753
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - acc: 0.8294 - loss: 0.3975 - val_acc: 0.8038 - val_loss: 0.4289
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.8619 - loss: 0.3351 - val_acc: 0.8015 - val_loss: 0.4428
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - acc: 0.8831 - loss: 0.2932 - val_acc: 0.7720 - val_loss: 0.4871
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - acc: 0.8977 - loss: 0.2689 - val_acc: 0.7807 - val_loss: 0.5475


In [33]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 63,461 (247.90 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 42,308 (165.27 KB)